const items=[
['Coffee','House Coffee','Fresh brewed house blend',2.99,3.79,'house-coffee.png'],['Coffee','Caffè Latte','Espresso with steamed milk',4.49,5.49,'coffee-latte.png'],['Coffee','Cappuccino','Espresso, steamed milk and foam',4.49,5.29,'capuccino.png'],['Coffee','Mocha','Espresso, chocolate and steamed milk',4.99,5.99,'mocha.png'],['Cold Drinks','Cold Brew','Smooth slow-steeped coffee',4.49,5.49,'cold-brew.png'],['Cold Drinks','Iced Chai Latte','Spiced chai with milk over ice',4.79,5.69,'iced-chai-latte.png'],['Breakfast','Egg & Cheese Croissant','Egg and cheese on a buttery croissant',6.99,6.99,'egg-cheese-croissant.png'],['Breakfast','Avocado Toast','Avocado, tomato and seasoning',7.99,7.99,'avocado-toast.png'],['Bakery','Butter Croissant','Fresh flaky croissant',3.49,3.49,'butter-croissant.png'],['Bakery','Blueberry Muffin','Soft muffin with blueberries',3.29,3.29,'blueberry-muffins.png'],['Lunch','Chicken Pesto Wrap','Chicken, pesto, greens and cheese',9.49,9.49,'chicken-pesto-wrap.png'],['Lunch','Veggie Panini','Vegetables, cheese and pesto',8.99,8.99,'veggiee-panini.png'],['Dessert','Chocolate Brownie','Rich chocolate brownie',3.99,3.99,'chocolate-brownie.png'],['Dessert','Cheesecake Slice','Classic creamy cheesecake',5.49,5.49,'cheese-cake-slice.png']];
let cart={}; const grid=document.querySelector('#menuGrid');
function render(filter='All'){grid.innerHTML=items.filter(x=>filter==='All'||x[0]===filter).map((x,i)=>`<article class="card"><img loading="lazy" src="${x[5]}" alt="${x[1]}"><div class="cardBody"><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><div class="priceRow"><b><span>Small $${x[3].toFixed(2)}</span><span>Large $${x[4].toFixed(2)}</span></b><a class="add" href="order.html" aria-label="Order ${x[1]}">+</a></div></div></article>`).join('')}
function add(name,price){if(!cart[name])cart[name]={price,qty:0};cart[name].qty++;drawCart();toast('Added '+name)}
function change(name,d){cart[name].qty+=d;if(cart[name].qty<=0)delete cart[name];drawCart()}
function drawCart(){const el=document.querySelector('#cart'), entries=Object.entries(cart);el.innerHTML=entries.length?entries.map(([n,v])=>`<div class="cartItem"><span><b>${n}</b><br><small>$${v.price.toFixed(2)} × ${v.qty}</small></span><button onclick="change('${n.replaceAll("'","\\'")}',-1)">−</button><button onclick="change('${n.replaceAll("'","\\'")}',1)">+</button></div>`).join(''):'<p class="empty">Your bag is waiting for something delicious.</p>';let s=entries.reduce((a,[,v])=>a+v.price*v.qty,0),t=s*.06;document.querySelector('#subtotal').textContent='$'+s.toFixed(2);document.querySelector('#tax').textContent='$'+t.toFixed(2);document.querySelector('#total').textContent='$'+(s+t).toFixed(2)}
function toast(t){let x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});document.querySelector('.menuBtn').onclick=()=>document.querySelector('.nav nav').classList.toggle('open');document.querySelectorAll('.nav nav a').forEach(a=>a.onclick=()=>document.querySelector('.nav nav').classList.remove('open'));document.querySelector('#checkout').onclick=()=>toast(Object.keys(cart).length?'Order demo ready — thank you!':'Add an item first');document.querySelector('#year').textContent=new Date().getFullYear();render();
